#ifndef MCU_ALARM_H
#define MCU_ALARM_H

#include <QByteArray>
#include "DataServices/Alert/DS_AlertDef.h"
#include "Common/Environment.h"
#include "Common/Util.h"

class McuAlarm
{
public:
    enum AlarmId
    {
        ALARM_ID_START = 0,

        ALARM_POST_BAD_SYSTEM_CRC = ALARM_ID_START,
        ALARM_POST_WATCH_DOG_RESET,
        ALARM_POST_LOW_POWER_RESET,
        ALARM_POST_12V_LEVEL_CHECK_FAILED,
        ALARM_POST_5V_LEVEL_CHECK_FAILED,
        ALARM_POST_36V_LEVEL_CHECK_FAILED,
        ALARM_POST_SC_VERSION_MISMATCH,
        ALARM_POST_STOP_BTN_PRESSED,
        ALARM_POST_ADVANCE_BTN_PRESSED,
        ALARM_POST_MCU_SC_CLOCK_CHK_FAILED,
        ALARM_POST_LED_VOLTAGE_CHECK_FAILED,

        ALARM_HCU_SHUTDOWN_FAILED,
        ALARM_STOP_BTN_FAULT,
        ALARM_VMT_OUT_RANGE,

        ALARM_BASE_OVER_TEMPERATURE,
        ALARM_PRESSURE_CAL_NEEDED_S0,
        ALARM_PRESSURE_CAL_NEEDED_C1,
        ALARM_PRESSURE_CAL_NEEDED_C2,

        ALARM_MOTOR_PLUNGER_CAL_NEEDED_S0,
        ALARM_MOTOR_CAL_NEEDED_S0,
        ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_S0,
        ALARM_MOTOR_ZERO_VOLUME_NOT_SET_S0,
        ALARM_MOTOR_ELECTRICAL_FAULT_S0,
        ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_S0,
        ALARM_MOTOR_HOME_SENSOR_FAULT_S0,

        ALARM_MOTOR_PLUNGER_CAL_NEEDED_C1,
        ALARM_MOTOR_CAL_NEEDED_C1,
        ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C1,
        ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C1,
        ALARM_MOTOR_ELECTRICAL_FAULT_C1,
        ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C1,
        ALARM_MOTOR_HOME_SENSOR_FAULT_C1,

        ALARM_MOTOR_PLUNGER_CAL_NEEDED_C2,
        ALARM_MOTOR_CAL_NEEDED_C2,
        ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C2,
        ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C2,
        ALARM_MOTOR_ELECTRICAL_FAULT_C2,
        ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C2,
        ALARM_MOTOR_HOME_SENSOR_FAULT_C2,

        ALARM_MOTOR_LOST_POSITION_S0,
        ALARM_MOTOR_LOST_POSITION_C1,
        ALARM_MOTOR_LOST_POSITION_C2,

        ALARM_INLET_AIR_CAL_NEEDED_S0,
        ALARM_INLET_AIR_SENSOR_FAULT_S0,

        ALARM_INLET_AIR_CAL_NEEDED_C1,
        ALARM_INLET_AIR_SENSOR_FAULT_C1,

        ALARM_INLET_AIR_CAL_NEEDED_C2,
        ALARM_INLET_AIR_SENSOR_FAULT_C2,

        ALARM_SUDS_CAL_NEEDED,
        ALARM_SUDS_SENSOR_FAULT,

        ALARM_OUTLET_AIR_SENSOR_FAULT,

        ALARM_DOOR_MECHANISM_FAILED,
        ALARM_DOOR_OPEN_FAULT,

        ALARM_SC_WATCH_DOG_RESET,
        ALARM_SC_CRC_FAULT,
        ALARM_SC_ENGAGEMENT_FAULT_S0,
        ALARM_SC_ENGAGEMENT_FAULT_C1,
        ALARM_SC_ENGAGEMENT_FAULT_C2,

        ALARM_SC_HBRIDGE_FAULT_S0,
        ALARM_SC_HBRIDGE_FAULT_C1,
        ALARM_SC_HBRIDGE_FAULT_C2,

        ALARM_SC_ENCODER_FAULT_S0,
        ALARM_SC_ENCODER_FAULT_C1,
        ALARM_SC_ENCODER_FAULT_C2,

        ALARM_SC_TIMEOUT_FAULT_S0,
        ALARM_SC_TIMEOUT_FAULT_C1,
        ALARM_SC_TIMEOUT_FAULT_C2,

        ALARM_SC_UNINTENDED_MOTION_DETECTED_S0,
        ALARM_SC_UNINTENDED_MOTION_DETECTED_C1,
        ALARM_SC_UNINTENDED_MOTION_DETECTED_C2,

        ALARM_I2C_MOTOR_MUX_FAULT,
        ALARM_I2C_SC_FAULT,

        ALARM_I2C_MOTOR_ADC_FAULT_S0,
        ALARM_I2C_MOTOR_IO_FAULT_S0,
        ALARM_I2C_MOTOR_FRAM_FAULT_S0,
        ALARM_I2C_MOTOR_BAD_ADDRESS_S0,

        ALARM_I2C_MOTOR_ADC_FAULT_C1,
        ALARM_I2C_MOTOR_IO_FAULT_C1,
        ALARM_I2C_MOTOR_FRAM_FAULT_C1,
        ALARM_I2C_MOTOR_BAD_ADDRESS_C1,

        ALARM_I2C_MOTOR_ADC_FAULT_C2,
        ALARM_I2C_MOTOR_IO_FAULT_C2,
        ALARM_I2C_MOTOR_FRAM_FAULT_C2,
        ALARM_I2C_MOTOR_BAD_ADDRESS_C2,

        ALARM_I2C_GENERAL_BASE_ADC_FAULT,
        ALARM_I2C_GENERAL_BASE_IO_FAULT,
        ALARM_I2C_GENERAL_BASE_FAN_FAULT,

        ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_A,
        ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_B,

        ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_CORE,
        ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_DOOR,

        ALARM_I2C_GENERAL_WASTE_CONTAINER_DETECT_COMM_FAULT,
        ALARM_I2C_GENERAL_WASTE_CONTAINER_LEVEL_COMM_FAULT,

        ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_S0,
        ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C1,
        ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C2,

        ALARM_I2C_GENERAL_SUDS_COMM_FAULT,
        ALARM_I2C_GENERAL_DOOR_LOCK_COMM_FAULT,

        ALARM_I2C_GENERAL_LED_SUDS_COMM_FAULT,
        ALARM_I2C_GENERAL_LED_DOOR_COMM_FAULT,
        ALARM_I2C_GENERAL_LED_TOP_COMM_FAULT,

        ALARM_I2C_GENERAL_MUX_FAULT,
        ALARM_I2C_GENERAL_BAD_ADDRESS,

        ALARM_HEAT_MAINTAINER_POWER_FAULT_CORE,
        ALARM_HEAT_MAINTAINER_POWER_FAULT_DOOR,
        ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_CORE,
        ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_DOOR,

        ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_S0,
        ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C1,
        ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C2,

        ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_S0,
        ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C1,
        ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C2,

        ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_S0,
        ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C1,
        ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C2,

        ALARM_ID_END,
        ALARM_ID_BAD = ALARM_ID_END
    };

    static QList<AlarmId> getAlarmListFromAlarmBits(QByteArray alarmBits)
    {
        QList<AlarmId> alarms;

        if (alarmBits.size() > 0)
        {
            int alarmSize = alarmBits.length();
            for (int id = ALARM_ID_START; id < ALARM_ID_END; id++)
            {
                int shiftedId = id % 8;
                int idShift = id / 8;
                int arrayIdx = alarmSize - idShift - 1;

                if ( (arrayIdx >= 0) && (arrayIdx <= alarmBits.size()) )
                {
                    quint8 bitmap = (quint8)alarmBits[arrayIdx];
                    if ((bitmap & ((quint8)1 << shiftedId)) != 0)
                    {
                        alarms.append((AlarmId)id);
                    }
                }
            }
        }
        return alarms;
    }

    static QByteArray getAlarmBitsFromAlarmIdSet(AlarmId alarmId)
    {
        QByteArray alarmBits;

        int shiftedId = alarmId % 8;
        int idShift = alarmId / 8;

        alarmBits.append((quint8)(1 << shiftedId));
        alarmBits.append(idShift, (quint8)0x0);

        return alarmBits;
    }

    static QString getAlarmName(AlarmId id)
    {
        switch (id)
        {
        case ALARM_POST_BAD_SYSTEM_CRC: return _L("ALARM_POST_BAD_SYSTEM_CRC");
        case ALARM_POST_WATCH_DOG_RESET: return _L("ALARM_POST_WATCH_DOG_RESET");
        case ALARM_POST_LOW_POWER_RESET: return _L("ALARM_POST_LOW_POWER_RESET");
        case ALARM_POST_12V_LEVEL_CHECK_FAILED: return _L("ALARM_POST_12V_LEVEL_CHECK_FAILED");
        case ALARM_POST_5V_LEVEL_CHECK_FAILED: return _L("ALARM_POST_5V_LEVEL_CHECK_FAILED");
        case ALARM_POST_36V_LEVEL_CHECK_FAILED: return _L("ALARM_POST_36V_LEVEL_CHECK_FAILED");
        case ALARM_POST_SC_VERSION_MISMATCH: return _L("ALARM_POST_SC_VERSION_MISMATCH");
        case ALARM_POST_STOP_BTN_PRESSED: return _L("ALARM_POST_STOP_BTN_PRESSED");
        case ALARM_POST_ADVANCE_BTN_PRESSED: return _L("ALARM_POST_ADVANCE_BTN_PRESSED");
        case ALARM_POST_MCU_SC_CLOCK_CHK_FAILED: return _L("ALARM_POST_MCU_SC_CLOCK_CHK_FAILED");
        case ALARM_POST_LED_VOLTAGE_CHECK_FAILED: return _L("ALARM_POST_LED_VOLTAGE_CHECK_FAILED");

        case ALARM_HCU_SHUTDOWN_FAILED: return _L("ALARM_HCU_SHUTDOWN_FAILED");
        case ALARM_STOP_BTN_FAULT: return _L("ALARM_STOP_BTN_FAULT");
        case ALARM_VMT_OUT_RANGE: return _L("ALARM_VMT_OUT_RANGE");

        case ALARM_BASE_OVER_TEMPERATURE: return _L("ALARM_BASE_OVER_TEMPERATURE");
        case ALARM_PRESSURE_CAL_NEEDED_S0: return _L("ALARM_PRESSURE_CAL_NEEDED_S0");
        case ALARM_PRESSURE_CAL_NEEDED_C1: return _L("ALARM_PRESSURE_CAL_NEEDED_C1");
        case ALARM_PRESSURE_CAL_NEEDED_C2: return _L("ALARM_PRESSURE_CAL_NEEDED_C2");

        case ALARM_MOTOR_PLUNGER_CAL_NEEDED_S0: return _L("ALARM_MOTOR_PLUNGER_CAL_NEEDED_S0");
        case ALARM_MOTOR_CAL_NEEDED_S0: return _L("ALARM_MOTOR_CAL_NEEDED_S0");
        case ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_S0: return _L("ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_S0");
        case ALARM_MOTOR_ZERO_VOLUME_NOT_SET_S0: return _L("ALARM_MOTOR_ZERO_VOLUME_NOT_SET_S0");
        case ALARM_MOTOR_ELECTRICAL_FAULT_S0: return _L("ALARM_MOTOR_ELECTRICAL_FAULT_S0");
        case ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_S0: return _L("ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_S0");
        case ALARM_MOTOR_HOME_SENSOR_FAULT_S0: return _L("ALARM_MOTOR_HOME_SENSOR_FAULT_S0");

        case ALARM_MOTOR_PLUNGER_CAL_NEEDED_C1: return _L("ALARM_MOTOR_PLUNGER_CAL_NEEDED_C1");
        case ALARM_MOTOR_CAL_NEEDED_C1: return _L("ALARM_MOTOR_CAL_NEEDED_C1");
        case ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C1: return _L("ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C1");
        case ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C1: return _L("ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C1");
        case ALARM_MOTOR_ELECTRICAL_FAULT_C1: return _L("ALARM_MOTOR_ELECTRICAL_FAULT_C1");
        case ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C1: return _L("ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C1");
        case ALARM_MOTOR_HOME_SENSOR_FAULT_C1: return _L("ALARM_MOTOR_HOME_SENSOR_FAULT_C1");

        case ALARM_MOTOR_PLUNGER_CAL_NEEDED_C2: return _L("ALARM_MOTOR_PLUNGER_CAL_NEEDED_C2");
        case ALARM_MOTOR_CAL_NEEDED_C2: return _L("ALARM_MOTOR_CAL_NEEDED_C2");
        case ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C2: return _L("ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C2");
        case ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C2: return _L("ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C2");
        case ALARM_MOTOR_ELECTRICAL_FAULT_C2: return _L("ALARM_MOTOR_ELECTRICAL_FAULT_C2");
        case ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C2: return _L("ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C2");
        case ALARM_MOTOR_HOME_SENSOR_FAULT_C2: return _L("ALARM_MOTOR_HOME_SENSOR_FAULT_C2");

        case ALARM_MOTOR_LOST_POSITION_S0: return _L("ALARM_MOTOR_LOST_POSITION_S0");
        case ALARM_MOTOR_LOST_POSITION_C1: return _L("ALARM_MOTOR_LOST_POSITION_C1");
        case ALARM_MOTOR_LOST_POSITION_C2: return _L("ALARM_MOTOR_LOST_POSITION_C2");

        case ALARM_INLET_AIR_CAL_NEEDED_S0: return _L("ALARM_INLET_AIR_CAL_NEEDED_S0");
        case ALARM_INLET_AIR_SENSOR_FAULT_S0: return _L("ALARM_INLET_AIR_SENSOR_FAULT_S0");

        case ALARM_INLET_AIR_CAL_NEEDED_C1: return _L("ALARM_INLET_AIR_CAL_NEEDED_C1");
        case ALARM_INLET_AIR_SENSOR_FAULT_C1: return _L("ALARM_INLET_AIR_SENSOR_FAULT_C1");

        case ALARM_INLET_AIR_CAL_NEEDED_C2: return _L("ALARM_INLET_AIR_CAL_NEEDED_C2");
        case ALARM_INLET_AIR_SENSOR_FAULT_C2: return _L("ALARM_INLET_AIR_SENSOR_FAULT_C2");

        case ALARM_SUDS_CAL_NEEDED: return _L("ALARM_SUDS_CAL_NEEDED");
        case ALARM_SUDS_SENSOR_FAULT: return _L("ALARM_SUDS_SENSOR_FAULT");

        case ALARM_OUTLET_AIR_SENSOR_FAULT: return _L("ALARM_OUTLET_AIR_SENSOR_FAULT");

        case ALARM_DOOR_MECHANISM_FAILED: return _L("ALARM_DOOR_MECHANISM_FAILED");
        case ALARM_DOOR_OPEN_FAULT: return _L("ALARM_DOOR_OPEN_FAULT");

        case ALARM_SC_WATCH_DOG_RESET: return _L("ALARM_SC_WATCH_DOG_RESET");
        case ALARM_SC_CRC_FAULT: return _L("ALARM_SC_CRC_FAULT");
        case ALARM_SC_ENGAGEMENT_FAULT_S0: return _L("ALARM_SC_ENGAGEMENT_FAULT_S0");
        case ALARM_SC_ENGAGEMENT_FAULT_C1: return _L("ALARM_SC_ENGAGEMENT_FAULT_C1");
        case ALARM_SC_ENGAGEMENT_FAULT_C2: return _L("ALARM_SC_ENGAGEMENT_FAULT_C2");

        case ALARM_SC_HBRIDGE_FAULT_S0: return _L("ALARM_SC_HBRIDGE_FAULT_S0");
        case ALARM_SC_HBRIDGE_FAULT_C1: return _L("ALARM_SC_HBRIDGE_FAULT_C1");
        case ALARM_SC_HBRIDGE_FAULT_C2: return _L("ALARM_SC_HBRIDGE_FAULT_C2");

        case ALARM_SC_ENCODER_FAULT_S0: return _L("ALARM_SC_ENCODER_FAULT_S0");
        case ALARM_SC_ENCODER_FAULT_C1: return _L("ALARM_SC_ENCODER_FAULT_C1");
        case ALARM_SC_ENCODER_FAULT_C2: return _L("ALARM_SC_ENCODER_FAULT_C2");

        case ALARM_SC_TIMEOUT_FAULT_S0: return _L("ALARM_SC_TIMEOUT_FAULT_S0");
        case ALARM_SC_TIMEOUT_FAULT_C1: return _L("ALARM_SC_TIMEOUT_FAULT_C1");
        case ALARM_SC_TIMEOUT_FAULT_C2: return _L("ALARM_SC_TIMEOUT_FAULT_C2");

        case ALARM_SC_UNINTENDED_MOTION_DETECTED_S0: return _L("ALARM_SC_UNINTENDED_MOTION_DETECTED_S0");
        case ALARM_SC_UNINTENDED_MOTION_DETECTED_C1: return _L("ALARM_SC_UNINTENDED_MOTION_DETECTED_C1");
        case ALARM_SC_UNINTENDED_MOTION_DETECTED_C2: return _L("ALARM_SC_UNINTENDED_MOTION_DETECTED_C2");

        case ALARM_I2C_MOTOR_MUX_FAULT: return _L("ALARM_I2C_MOTOR_MUX_FAULT");
        case ALARM_I2C_SC_FAULT: return _L("ALARM_I2C_SC_FAULT");

        case ALARM_I2C_MOTOR_ADC_FAULT_S0: return _L("ALARM_I2C_MOTOR_ADC_FAULT_S0");
        case ALARM_I2C_MOTOR_IO_FAULT_S0: return _L("ALARM_I2C_MOTOR_IO_FAULT_S0");
        case ALARM_I2C_MOTOR_FRAM_FAULT_S0: return _L("ALARM_I2C_MOTOR_FRAM_FAULT_S0");
        case ALARM_I2C_MOTOR_BAD_ADDRESS_S0: return _L("ALARM_I2C_MOTOR_BAD_ADDRESS_S0");

        case ALARM_I2C_MOTOR_ADC_FAULT_C1: return _L("ALARM_I2C_MOTOR_ADC_FAULT_C1");
        case ALARM_I2C_MOTOR_IO_FAULT_C1: return _L("ALARM_I2C_MOTOR_IO_FAULT_C1");
        case ALARM_I2C_MOTOR_FRAM_FAULT_C1: return _L("ALARM_I2C_MOTOR_FRAM_FAULT_C1");
        case ALARM_I2C_MOTOR_BAD_ADDRESS_C1: return _L("ALARM_I2C_MOTOR_BAD_ADDRESS_C1");

        case ALARM_I2C_MOTOR_ADC_FAULT_C2: return _L("ALARM_I2C_MOTOR_ADC_FAULT_C2");
        case ALARM_I2C_MOTOR_IO_FAULT_C2: return _L("ALARM_I2C_MOTOR_IO_FAULT_C2");
        case ALARM_I2C_MOTOR_FRAM_FAULT_C2: return _L("ALARM_I2C_MOTOR_FRAM_FAULT_C2");
        case ALARM_I2C_MOTOR_BAD_ADDRESS_C2: return _L("ALARM_I2C_MOTOR_BAD_ADDRESS_C2");

        case ALARM_I2C_GENERAL_BASE_ADC_FAULT: return _L("ALARM_I2C_GENERAL_BASE_ADC_FAULT");
        case ALARM_I2C_GENERAL_BASE_IO_FAULT: return _L("ALARM_I2C_GENERAL_BASE_IO_FAULT");
        case ALARM_I2C_GENERAL_BASE_FAN_FAULT: return _L("ALARM_I2C_GENERAL_BASE_FAN_FAULT");

        case ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_A: return _L("ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_A");
        case ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_B: return _L("ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_B");

        case ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_CORE: return _L("ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_CORE");
        case ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_DOOR: return _L("ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_DOOR");

        case ALARM_I2C_GENERAL_WASTE_CONTAINER_DETECT_COMM_FAULT: return _L("ALARM_I2C_GENERAL_WASTE_CONTAINER_DETECT_COMM_FAULT");
        case ALARM_I2C_GENERAL_WASTE_CONTAINER_LEVEL_COMM_FAULT: return _L("ALARM_I2C_GENERAL_WASTE_CONTAINER_LEVEL_COMM_FAULT");

        case ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_S0: return _L("ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_S0");
        case ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C1: return _L("ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C1");
        case ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C2: return _L("ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C2");

        case ALARM_I2C_GENERAL_SUDS_COMM_FAULT: return _L("ALARM_I2C_GENERAL_SUDS_COMM_FAULT");
        case ALARM_I2C_GENERAL_DOOR_LOCK_COMM_FAULT: return _L("ALARM_I2C_GENERAL_DOOR_LOCK_COMM_FAULT");

        case ALARM_I2C_GENERAL_LED_SUDS_COMM_FAULT: return _L("ALARM_I2C_GENERAL_LED_SUDS_COMM_FAULT");
        case ALARM_I2C_GENERAL_LED_DOOR_COMM_FAULT: return _L("ALARM_I2C_GENERAL_LED_DOOR_COMM_FAULT");
        case ALARM_I2C_GENERAL_LED_TOP_COMM_FAULT: return _L("ALARM_I2C_GENERAL_LED_TOP_COMM_FAULT");

        case ALARM_I2C_GENERAL_MUX_FAULT: return _L("ALARM_I2C_GENERAL_MUX_FAULT");
        case ALARM_I2C_GENERAL_BAD_ADDRESS: return _L("ALARM_I2C_GENERAL_BAD_ADDRESS");

        case ALARM_HEAT_MAINTAINER_POWER_FAULT_CORE: return _L("ALARM_HEAT_MAINTAINER_POWER_FAULT_CORE");
        case ALARM_HEAT_MAINTAINER_POWER_FAULT_DOOR: return _L("ALARM_HEAT_MAINTAINER_POWER_FAULT_DOOR");
        case ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_CORE: return _L("ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_CORE");
        case ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_DOOR: return _L("ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_DOOR");

        case ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_S0: return _L("ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_S0");
        case ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C1: return _L("ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C1");
        case ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C2: return _L("ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C2");

        case ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_S0: return _L("ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_S0");
        case ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C1: return _L("ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C1");
        case ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C2: return _L("ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C2");

        case ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_S0: return _L("ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_S0");
        case ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C1: return _L("ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C1");
        case ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C2: return _L("ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C2");

        default: return QString().asprintf("ALARM_BAD_ID%d", id);
        }
    }

    static AlarmId getAlarmId(QString alarmName)
    {
        if (alarmName == "ALARM_ID_START") return ALARM_ID_START;
        else if (alarmName == "ALARM_POST_BAD_SYSTEM_CRC") return ALARM_POST_BAD_SYSTEM_CRC;
        else if (alarmName == "ALARM_POST_WATCH_DOG_RESET") return ALARM_POST_WATCH_DOG_RESET;
        else if (alarmName == "ALARM_POST_LOW_POWER_RESET") return ALARM_POST_LOW_POWER_RESET;
        else if (alarmName == "ALARM_POST_12V_LEVEL_CHECK_FAILED") return ALARM_POST_12V_LEVEL_CHECK_FAILED;
        else if (alarmName == "ALARM_POST_5V_LEVEL_CHECK_FAILED") return ALARM_POST_5V_LEVEL_CHECK_FAILED;
        else if (alarmName == "ALARM_POST_36V_LEVEL_CHECK_FAILED") return ALARM_POST_36V_LEVEL_CHECK_FAILED;
        else if (alarmName == "ALARM_POST_SC_VERSION_MISMATCH") return ALARM_POST_SC_VERSION_MISMATCH;
        else if (alarmName == "ALARM_POST_STOP_BTN_PRESSED") return ALARM_POST_STOP_BTN_PRESSED;
        else if (alarmName == "ALARM_POST_ADVANCE_BTN_PRESSED") return ALARM_POST_ADVANCE_BTN_PRESSED;
        else if (alarmName == "ALARM_POST_MCU_SC_CLOCK_CHK_FAILED") return ALARM_POST_MCU_SC_CLOCK_CHK_FAILED;
        else if (alarmName == "ALARM_POST_LED_VOLTAGE_CHECK_FAILED") return ALARM_POST_LED_VOLTAGE_CHECK_FAILED;

        else if (alarmName == "ALARM_HCU_SHUTDOWN_FAILED") return ALARM_HCU_SHUTDOWN_FAILED;
        else if (alarmName == "ALARM_STOP_BTN_FAULT") return ALARM_STOP_BTN_FAULT;
        else if (alarmName == "ALARM_VMT_OUT_RANGE") return ALARM_VMT_OUT_RANGE;

        else if (alarmName == "ALARM_BASE_OVER_TEMPERATURE") return ALARM_BASE_OVER_TEMPERATURE;
        else if (alarmName == "ALARM_PRESSURE_CAL_NEEDED_S0") return ALARM_PRESSURE_CAL_NEEDED_S0;
        else if (alarmName == "ALARM_PRESSURE_CAL_NEEDED_C1") return ALARM_PRESSURE_CAL_NEEDED_C1;
        else if (alarmName == "ALARM_PRESSURE_CAL_NEEDED_C2") return ALARM_PRESSURE_CAL_NEEDED_C2;

        else if (alarmName == "ALARM_MOTOR_PLUNGER_CAL_NEEDED_S0") return ALARM_MOTOR_PLUNGER_CAL_NEEDED_S0;
        else if (alarmName == "ALARM_MOTOR_CAL_NEEDED_S0") return ALARM_MOTOR_CAL_NEEDED_S0;
        else if (alarmName == "ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_S0") return ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_S0;
        else if (alarmName == "ALARM_MOTOR_ZERO_VOLUME_NOT_SET_S0") return ALARM_MOTOR_ZERO_VOLUME_NOT_SET_S0;
        else if (alarmName == "ALARM_MOTOR_ELECTRICAL_FAULT_S0") return ALARM_MOTOR_ELECTRICAL_FAULT_S0;
        else if (alarmName == "ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_S0") return ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_S0;
        else if (alarmName == "ALARM_MOTOR_HOME_SENSOR_FAULT_S0") return ALARM_MOTOR_HOME_SENSOR_FAULT_S0;

        else if (alarmName == "ALARM_MOTOR_PLUNGER_CAL_NEEDED_C1") return ALARM_MOTOR_PLUNGER_CAL_NEEDED_C1;
        else if (alarmName == "ALARM_MOTOR_CAL_NEEDED_C1") return ALARM_MOTOR_CAL_NEEDED_C1;
        else if (alarmName == "ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C1") return ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C1;
        else if (alarmName == "ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C1") return ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C1;
        else if (alarmName == "ALARM_MOTOR_ELECTRICAL_FAULT_C1") return ALARM_MOTOR_ELECTRICAL_FAULT_C1;
        else if (alarmName == "ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C1") return ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C1;
        else if (alarmName == "ALARM_MOTOR_HOME_SENSOR_FAULT_C1") return ALARM_MOTOR_HOME_SENSOR_FAULT_C1;

        else if (alarmName == "ALARM_MOTOR_PLUNGER_CAL_NEEDED_C2") return ALARM_MOTOR_PLUNGER_CAL_NEEDED_C2;
        else if (alarmName == "ALARM_MOTOR_CAL_NEEDED_C2") return ALARM_MOTOR_CAL_NEEDED_C2;
        else if (alarmName == "ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C2") return ALARM_MOTOR_HALL_SENSOR_OUT_RANGE_C2;
        else if (alarmName == "ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C2") return ALARM_MOTOR_ZERO_VOLUME_NOT_SET_C2;
        else if (alarmName == "ALARM_MOTOR_ELECTRICAL_FAULT_C2") return ALARM_MOTOR_ELECTRICAL_FAULT_C2;
        else if (alarmName == "ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C2") return ALARM_MOTOR_FINAL_DRIVE_ENCODER_FAULT_C2;
        else if (alarmName == "ALARM_MOTOR_HOME_SENSOR_FAULT_C2") return ALARM_MOTOR_HOME_SENSOR_FAULT_C2;

        else if (alarmName == "ALARM_MOTOR_LOST_POSITION_S0") return ALARM_MOTOR_LOST_POSITION_S0;
        else if (alarmName == "ALARM_MOTOR_LOST_POSITION_C1") return ALARM_MOTOR_LOST_POSITION_C1;
        else if (alarmName == "ALARM_MOTOR_LOST_POSITION_C2") return ALARM_MOTOR_LOST_POSITION_C2;

        else if (alarmName == "ALARM_INLET_AIR_CAL_NEEDED_S0") return ALARM_INLET_AIR_CAL_NEEDED_S0;
        else if (alarmName == "ALARM_INLET_AIR_SENSOR_FAULT_S0") return ALARM_INLET_AIR_SENSOR_FAULT_S0;

        else if (alarmName == "ALARM_INLET_AIR_CAL_NEEDED_C1") return ALARM_INLET_AIR_CAL_NEEDED_C1;
        else if (alarmName == "ALARM_INLET_AIR_SENSOR_FAULT_C1") return ALARM_INLET_AIR_SENSOR_FAULT_C1;

        else if (alarmName == "ALARM_INLET_AIR_CAL_NEEDED_C2") return ALARM_INLET_AIR_CAL_NEEDED_C2;
        else if (alarmName == "ALARM_INLET_AIR_SENSOR_FAULT_C2") return ALARM_INLET_AIR_SENSOR_FAULT_C2;

        else if (alarmName == "ALARM_SUDS_CAL_NEEDED") return ALARM_SUDS_CAL_NEEDED;
        else if (alarmName == "ALARM_SUDS_SENSOR_FAULT") return ALARM_SUDS_SENSOR_FAULT;

        else if (alarmName == "ALARM_OUTLET_AIR_SENSOR_FAULT") return ALARM_OUTLET_AIR_SENSOR_FAULT;

        else if (alarmName == "ALARM_DOOR_MECHANISM_FAILED") return ALARM_DOOR_MECHANISM_FAILED;
        else if (alarmName == "ALARM_DOOR_OPEN_FAULT") return ALARM_DOOR_OPEN_FAULT;

        else if (alarmName == "ALARM_SC_WATCH_DOG_RESET") return ALARM_SC_WATCH_DOG_RESET;
        else if (alarmName == "ALARM_SC_CRC_FAULT") return ALARM_SC_CRC_FAULT;
        else if (alarmName == "ALARM_SC_ENGAGEMENT_FAULT_S0") return ALARM_SC_ENGAGEMENT_FAULT_S0;
        else if (alarmName == "ALARM_SC_ENGAGEMENT_FAULT_C1") return ALARM_SC_ENGAGEMENT_FAULT_C1;
        else if (alarmName == "ALARM_SC_ENGAGEMENT_FAULT_C2") return ALARM_SC_ENGAGEMENT_FAULT_C2;

        else if (alarmName == "ALARM_SC_HBRIDGE_FAULT_S0") return ALARM_SC_HBRIDGE_FAULT_S0;
        else if (alarmName == "ALARM_SC_HBRIDGE_FAULT_C1") return ALARM_SC_HBRIDGE_FAULT_C1;
        else if (alarmName == "ALARM_SC_HBRIDGE_FAULT_C2") return ALARM_SC_HBRIDGE_FAULT_C2;

        else if (alarmName == "ALARM_SC_ENCODER_FAULT_S0") return ALARM_SC_ENCODER_FAULT_S0;
        else if (alarmName == "ALARM_SC_ENCODER_FAULT_C1") return ALARM_SC_ENCODER_FAULT_C1;
        else if (alarmName == "ALARM_SC_ENCODER_FAULT_C2") return ALARM_SC_ENCODER_FAULT_C2;

        else if (alarmName == "ALARM_SC_TIMEOUT_FAULT_S0") return ALARM_SC_TIMEOUT_FAULT_S0;
        else if (alarmName == "ALARM_SC_TIMEOUT_FAULT_C1") return ALARM_SC_TIMEOUT_FAULT_C1;
        else if (alarmName == "ALARM_SC_TIMEOUT_FAULT_C2") return ALARM_SC_TIMEOUT_FAULT_C2;

        else if (alarmName == "ALARM_SC_UNINTENDED_MOTION_DETECTED_S0") return ALARM_SC_UNINTENDED_MOTION_DETECTED_S0;
        else if (alarmName == "ALARM_SC_UNINTENDED_MOTION_DETECTED_C1") return ALARM_SC_UNINTENDED_MOTION_DETECTED_C1;
        else if (alarmName == "ALARM_SC_UNINTENDED_MOTION_DETECTED_C2") return ALARM_SC_UNINTENDED_MOTION_DETECTED_C2;

        else if (alarmName == "ALARM_I2C_MOTOR_MUX_FAULT") return ALARM_I2C_MOTOR_MUX_FAULT;
        else if (alarmName == "ALARM_I2C_SC_FAULT") return ALARM_I2C_SC_FAULT;

        else if (alarmName == "ALARM_I2C_MOTOR_ADC_FAULT_S0") return ALARM_I2C_MOTOR_ADC_FAULT_S0;
        else if (alarmName == "ALARM_I2C_MOTOR_IO_FAULT_S0") return ALARM_I2C_MOTOR_IO_FAULT_S0;
        else if (alarmName == "ALARM_I2C_MOTOR_FRAM_FAULT_S0") return ALARM_I2C_MOTOR_FRAM_FAULT_S0;
        else if (alarmName == "ALARM_I2C_MOTOR_BAD_ADDRESS_S0") return ALARM_I2C_MOTOR_BAD_ADDRESS_S0;

        else if (alarmName == "ALARM_I2C_MOTOR_ADC_FAULT_C1") return ALARM_I2C_MOTOR_ADC_FAULT_C1;
        else if (alarmName == "ALARM_I2C_MOTOR_IO_FAULT_C1") return ALARM_I2C_MOTOR_IO_FAULT_C1;
        else if (alarmName == "ALARM_I2C_MOTOR_FRAM_FAULT_C1") return ALARM_I2C_MOTOR_FRAM_FAULT_C1;
        else if (alarmName == "ALARM_I2C_MOTOR_BAD_ADDRESS_C1") return ALARM_I2C_MOTOR_BAD_ADDRESS_C1;

        else if (alarmName == "ALARM_I2C_MOTOR_ADC_FAULT_C2") return ALARM_I2C_MOTOR_ADC_FAULT_C2;
        else if (alarmName == "ALARM_I2C_MOTOR_IO_FAULT_C2") return ALARM_I2C_MOTOR_IO_FAULT_C2;
        else if (alarmName == "ALARM_I2C_MOTOR_FRAM_FAULT_C2") return ALARM_I2C_MOTOR_FRAM_FAULT_C2;
        else if (alarmName == "ALARM_I2C_MOTOR_BAD_ADDRESS_C2") return ALARM_I2C_MOTOR_BAD_ADDRESS_C2;

        else if (alarmName == "ALARM_I2C_GENERAL_BASE_ADC_FAULT") return ALARM_I2C_GENERAL_BASE_ADC_FAULT;
        else if (alarmName == "ALARM_I2C_GENERAL_BASE_IO_FAULT") return ALARM_I2C_GENERAL_BASE_IO_FAULT;
        else if (alarmName == "ALARM_I2C_GENERAL_BASE_FAN_FAULT") return ALARM_I2C_GENERAL_BASE_FAN_FAULT;

        else if (alarmName == "ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_A") return ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_A;
        else if (alarmName == "ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_B") return ALARM_I2C_GENERAL_BATTERY_MANAGEMENT_SYSTEM_B;

        else if (alarmName == "ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_CORE") return ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_CORE;
        else if (alarmName == "ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_DOOR") return ALARM_I2C_GENERAL_HEAT_MAINTAINER_COMM_FAULT_DOOR;

        else if (alarmName == "ALARM_I2C_GENERAL_WASTE_CONTAINER_DETECT_COMM_FAULT") return ALARM_I2C_GENERAL_WASTE_CONTAINER_DETECT_COMM_FAULT;
        else if (alarmName == "ALARM_I2C_GENERAL_WASTE_CONTAINER_LEVEL_COMM_FAULT") return ALARM_I2C_GENERAL_WASTE_CONTAINER_LEVEL_COMM_FAULT;

        else if (alarmName == "ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_S0") return ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_S0;
        else if (alarmName == "ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C1") return ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C1;
        else if (alarmName == "ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C2") return ALARM_I2C_GENERAL_INLET_AIR_DETECT_COMM_FAULT_C2;

        else if (alarmName == "ALARM_I2C_GENERAL_SUDS_COMM_FAULT") return ALARM_I2C_GENERAL_SUDS_COMM_FAULT;
        else if (alarmName == "ALARM_I2C_GENERAL_DOOR_LOCK_COMM_FAULT") return ALARM_I2C_GENERAL_DOOR_LOCK_COMM_FAULT;

        else if (alarmName == "ALARM_I2C_GENERAL_LED_SUDS_COMM_FAULT") return ALARM_I2C_GENERAL_LED_SUDS_COMM_FAULT;
        else if (alarmName == "ALARM_I2C_GENERAL_LED_DOOR_COMM_FAULT") return ALARM_I2C_GENERAL_LED_DOOR_COMM_FAULT;
        else if (alarmName == "ALARM_I2C_GENERAL_LED_TOP_COMM_FAULT") return ALARM_I2C_GENERAL_LED_TOP_COMM_FAULT;

        else if (alarmName == "ALARM_I2C_GENERAL_MUX_FAULT") return ALARM_I2C_GENERAL_MUX_FAULT;
        else if (alarmName == "ALARM_I2C_GENERAL_BAD_ADDRESS") return ALARM_I2C_GENERAL_BAD_ADDRESS;

        else if (alarmName == "ALARM_HEAT_MAINTAINER_POWER_FAULT_CORE") return ALARM_HEAT_MAINTAINER_POWER_FAULT_CORE;
        else if (alarmName == "ALARM_HEAT_MAINTAINER_POWER_FAULT_DOOR") return ALARM_HEAT_MAINTAINER_POWER_FAULT_DOOR;
        else if (alarmName == "ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_CORE") return ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_CORE;
        else if (alarmName == "ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_DOOR") return ALARM_HEAT_MAINTAINER_DIGITAL_POWER_FAULT_DOOR;

        else if (alarmName == "ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_S0") return ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_S0;
        else if (alarmName == "ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C1") return ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C1;
        else if (alarmName == "ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C2") return ALARM_I2C_MOTOR_PLUNGER_POT_FAULT_C2;

        else if (alarmName == "ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_S0") return ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_S0;
        else if (alarmName == "ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C1") return ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C1;
        else if (alarmName == "ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C2") return ALARM_I2C_MOTOR_LOCK_UINLOCK_POT_FAULT_C2;

        else if (alarmName == "ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_S0") return ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_S0;
        else if (alarmName == "ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C1") return ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C1;
        else if (alarmName == "ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C2") return ALARM_MOTOR_UNEXPECTED_PLUGNER_TRANSITION_C2;

        else return ALARM_ID_BAD;
    }
};

#endif // MCU_ALARM_H



