#ifndef DS_CAPABILITIES_H
#define DS_CAPABILITIES_H

#include <QObject>
#include <QMutex>
#include <QString>
#include "Common/Common.h"
#include "Common/Config.h"
#include "DataServices/DataServicesMacros.h"

class DS_Capabilities : public QObject
{
    Q_OBJECT

public:
    explicit DS_Capabilities(QObject *parent = 0, EnvGlobal *env_ = NULL);
    ~DS_Capabilities();
    QVariantMap getConfigs(QString *err = NULL);
    void setConfigs(QVariantMap configs, bool setChangedAt, QString *err);

    static void registerDataTypesForThread()
    {
        qRegisterMetaType<Config::Item>("Config::Item");
    }

signals:
    void signalConfigChanged();

    // Define OUTGOING Signals (i.e. WHEN DATA CHANGED)
    CREATE_CONFIG_CHANGED_SIGNAL(General_ScreenMode)
    CREATE_CONFIG_CHANGED_SIGNAL(General_StartVideoEnabled)
    CREATE_CONFIG_CHANGED_SIGNAL(General_DisplayDeviceManagerDuringInjection)
    CREATE_CONFIG_CHANGED_SIGNAL(General_WebApplicationEnabled)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_McuSimulationEnabled)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_AdvanceModeDevModeEnabled)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_HCUMonitorEnabled)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_ContinuousExamsTestEnabled)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_ContinuousExamsTestLimit)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_ContinuousExamsTestExamStartDelaySec)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_ContinuousExamsTestSelectedPlans)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_ContinuousExamsTestActiveContrastLocation)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_DebugMode)
    CREATE_CONFIG_CHANGED_SIGNAL(Developer_WifiDriver)
    CREATE_CONFIG_CHANGED_SIGNAL(DateTime_SystemDateTime)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_NewMudsVolOffset)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_FillFlowRate)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_CalSyringeSlackRequiredVol)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_CalSyringeAirCheckFlow)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_CalSyringeAirCheckTargetPressure)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_ReusedMudsValidationOffset)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_SyringeVolumeAdjustmentLimitMin)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_SyringeVolumeAdjustmentLimitMax)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_SyringeVolumeSwitchOverAdjustmentLimitMin)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_FluidRemovalFlow)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_PatientLineVolume)
    CREATE_CONFIG_CHANGED_SIGNAL(FluidControl_PatientLineVolumeExtended)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_AutoPrimeFlow)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_AutoPrimeVol)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_ExtendedAutoPrimeVol)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_ManualPrimeFlow)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_SyringePrimeVol)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_SyringePrimeFlow)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_PrimeSalinePressureDecayWait)
    CREATE_CONFIG_CHANGED_SIGNAL(Prime_PrimeContrastPressureDecayWait)
    CREATE_CONFIG_CHANGED_SIGNAL(AirCheck_SyringeAirCheckRequiredVol)
    CREATE_CONFIG_CHANGED_SIGNAL(AirCheck_SyringeAirCheckFlow)
    CREATE_CONFIG_CHANGED_SIGNAL(AirCheck_SyringeAirCheckTargetPressure)
    CREATE_CONFIG_CHANGED_SIGNAL(AirCheck_SyringeAirRecoveryPrimeExtraVol)
    CREATE_CONFIG_CHANGED_SIGNAL(AirCheck_SyringeAirRecoveryPrimeExtraVolMaxAir)
    CREATE_CONFIG_CHANGED_SIGNAL(AirCheck_SyringeAirRecoveryPrimeFlow)
    CREATE_CONFIG_CHANGED_SIGNAL(AirCheck_SyringeAirRecoveryMaxAirAmount)
    CREATE_CONFIG_CHANGED_SIGNAL(Preload_SalineVolume)
    CREATE_CONFIG_CHANGED_SIGNAL(Preload_Contrast1Volume)
    CREATE_CONFIG_CHANGED_SIGNAL(Preload_Contrast2Volume)
    CREATE_CONFIG_CHANGED_SIGNAL(Preload_SalineVolumeExtended)
    CREATE_CONFIG_CHANGED_SIGNAL(Preload_Contrast1VolumeExtended)
    CREATE_CONFIG_CHANGED_SIGNAL(Preload_Contrast2VolumeExtended)
    CREATE_CONFIG_CHANGED_SIGNAL(Preload_PreloadFlowRate)
    CREATE_CONFIG_CHANGED_SIGNAL(Network_EthernetInterface)
    CREATE_CONFIG_CHANGED_SIGNAL(Network_WifiInterface)
    CREATE_CONFIG_CHANGED_SIGNAL(Network_DosAttackMonitorEnabled)
    CREATE_CONFIG_CHANGED_SIGNAL(Network_SpontaneousDigestInterval)
    CREATE_CONFIG_CHANGED_SIGNAL(Network_SpontaneousDigestOnInterval)
    CREATE_CONFIG_CHANGED_SIGNAL(Network_SpontaneousDigestOffInterval)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_DigestPollingInterval)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_MaxErrorLimitLow)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_TemperatureLimitLow)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_TemperatureLimitHigh)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_CycleCountLimit)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_StateOfHealthLowLimit)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_PFResetTrialLimit)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_ShippingModeAirTargetChargedLevel)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_ShippingModeLandTargetChargedLevel)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_ShippingModeSeaTargetChargedLevel)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_EnableBatteryTestMode)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_AQD_BatteryPackA_MaxError_Trigger)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_AQD_BatteryPackB_MaxError_Trigger)
    CREATE_CONFIG_CHANGED_SIGNAL(BMS_AQD_OtherBatteryChargeLimit)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_AlertBufferLimit)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPortExposedLimitSeconds)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPortExposedAfterUserAckLimitSeconds)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPrimeDataSlopeStartTime)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPrimeDataSlopeEndTime)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPrimeDataSteadyStateStartTime)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPrimeDataSteadyStateEndTime)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPrimeDataSlopeCutoffLow)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_SUDSPrimeDataSlopeCutoffHigh)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_ContrastBottleCountReached_Limit)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_NewBottleMinimumFillVolume)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_McuDiagnosticEventTriggerCount)
    CREATE_CONFIG_CHANGED_SIGNAL(Alert_McuDiagnosticEventTriggerPeriod)
    CREATE_CONFIG_CHANGED_SIGNAL(Logging_ImrServerHcuDigest)
    CREATE_CONFIG_CHANGED_SIGNAL(Logging_ImrServerDumpBodySizeLimit)
    CREATE_CONFIG_CHANGED_SIGNAL(Logging_McuInjectDigest)
    CREATE_CONFIG_CHANGED_SIGNAL(Calibration_PressureCalMaxTravelUntilEngaged)
    CREATE_CONFIG_CHANGED_SIGNAL(Calibration_PressureCalMaxTravelUntilDataReady)
    CREATE_CONFIG_CHANGED_SIGNAL(Calibration_PressureCalInjectVolume)
    CREATE_CONFIG_CHANGED_SIGNAL(Calibration_PressureCalADCRangeMin)
    CREATE_CONFIG_CHANGED_SIGNAL(Calibration_PressureCalADCRangeMax)
    CREATE_CONFIG_CHANGED_SIGNAL(Calibration_PressureCalMovingMeanSampleSize)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_MaxSteps)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_MaxPhases)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPhaseFlowRateMin)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPhaseFlowRateMax)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPhaseVolMin)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPhaseVolMax)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPhaseDelayMsMin)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPhaseDelayMsMax)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPressureKpaMin)
    CREATE_CONFIG_CHANGED_SIGNAL(Hidden_InjectionPressureKpaMax)

    // Creates GET/SET Properties
    CREATE_CONFIG_MEMBERS(General_ScreenMode)
    CREATE_CONFIG_MEMBERS_EX(General_StartVideoEnabled, bool, toBool)
    CREATE_CONFIG_MEMBERS(General_DisplayDeviceManagerDuringInjection)
    CREATE_CONFIG_MEMBERS_EX(General_WebApplicationEnabled, bool, toBool)
    CREATE_CONFIG_MEMBERS_EX(Developer_McuSimulationEnabled, bool, toBool)
    CREATE_CONFIG_MEMBERS_EX(Developer_AdvanceModeDevModeEnabled, bool, toBool)
    CREATE_CONFIG_MEMBERS(Developer_HCUMonitorEnabled)
    CREATE_CONFIG_MEMBERS(Developer_ContinuousExamsTestEnabled)
    CREATE_CONFIG_MEMBERS_EX(Developer_ContinuousExamsTestLimit, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Developer_ContinuousExamsTestExamStartDelaySec, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Developer_ContinuousExamsTestSelectedPlans, QString, toString)
    CREATE_CONFIG_MEMBERS_EX(Developer_ContinuousExamsTestActiveContrastLocation, QString, toString)
    CREATE_CONFIG_MEMBERS_EX(Developer_DebugMode, QString, toString)
    CREATE_CONFIG_MEMBERS_EX(Developer_WifiDriver, QString, toString)
    CREATE_CONFIG_MEMBERS(DateTime_SystemDateTime)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_NewMudsVolOffset, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_FillFlowRate, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_CalSyringeSlackRequiredVol, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_CalSyringeAirCheckFlow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_CalSyringeAirCheckTargetPressure, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_ReusedMudsValidationOffset, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_SyringeVolumeAdjustmentLimitMin, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_SyringeVolumeAdjustmentLimitMax, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_SyringeVolumeSwitchOverAdjustmentLimitMin, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_FluidRemovalFlow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_PatientLineVolume, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(FluidControl_PatientLineVolumeExtended, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Prime_AutoPrimeFlow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Prime_AutoPrimeVol, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Prime_ExtendedAutoPrimeVol, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Prime_ManualPrimeFlow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Prime_SyringePrimeVol, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Prime_SyringePrimeFlow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Prime_PrimeSalinePressureDecayWait, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Prime_PrimeContrastPressureDecayWait, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(AirCheck_SyringeAirCheckRequiredVol, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(AirCheck_SyringeAirCheckFlow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(AirCheck_SyringeAirCheckTargetPressure, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(AirCheck_SyringeAirRecoveryPrimeExtraVol, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(AirCheck_SyringeAirRecoveryPrimeExtraVolMaxAir, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(AirCheck_SyringeAirRecoveryPrimeFlow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(AirCheck_SyringeAirRecoveryMaxAirAmount, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Preload_SalineVolume, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Preload_Contrast1Volume, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Preload_Contrast2Volume, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Preload_SalineVolumeExtended, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Preload_Contrast1VolumeExtended, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Preload_Contrast2VolumeExtended, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Preload_PreloadFlowRate, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Network_EthernetInterface, QString, toString)
    CREATE_CONFIG_MEMBERS_EX(Network_WifiInterface, QString, toString)
    CREATE_CONFIG_MEMBERS_EX(Network_DosAttackMonitorEnabled, bool, toBool)
    CREATE_CONFIG_MEMBERS_EX(Network_SpontaneousDigestInterval, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Network_SpontaneousDigestOnInterval, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Network_SpontaneousDigestOffInterval, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(BMS_DigestPollingInterval, int, toInt)
    CREATE_CONFIG_MEMBERS(BMS_MaxErrorLimitLow)
    CREATE_CONFIG_MEMBERS_EX(BMS_TemperatureLimitLow, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(BMS_TemperatureLimitHigh, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(BMS_CycleCountLimit, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(BMS_StateOfHealthLowLimit, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(BMS_PFResetTrialLimit, int, toInt)
    CREATE_CONFIG_MEMBERS(BMS_ShippingModeAirTargetChargedLevel)
    CREATE_CONFIG_MEMBERS(BMS_ShippingModeLandTargetChargedLevel)
    CREATE_CONFIG_MEMBERS(BMS_ShippingModeSeaTargetChargedLevel)
    CREATE_CONFIG_MEMBERS(BMS_EnableBatteryTestMode)
    CREATE_CONFIG_MEMBERS(BMS_AQD_BatteryPackA_MaxError_Trigger)
    CREATE_CONFIG_MEMBERS(BMS_AQD_BatteryPackB_MaxError_Trigger)
    CREATE_CONFIG_MEMBERS(BMS_AQD_OtherBatteryChargeLimit)
    CREATE_CONFIG_MEMBERS_EX(Alert_AlertBufferLimit, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPortExposedLimitSeconds, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPortExposedAfterUserAckLimitSeconds, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPrimeDataSlopeStartTime, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPrimeDataSlopeEndTime, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPrimeDataSteadyStateStartTime, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPrimeDataSteadyStateEndTime, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPrimeDataSlopeCutoffLow, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Alert_SUDSPrimeDataSlopeCutoffHigh, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Alert_ContrastBottleCountReached_Limit, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_NewBottleMinimumFillVolume, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Alert_McuDiagnosticEventTriggerCount, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Alert_McuDiagnosticEventTriggerPeriod, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Logging_ImrServerHcuDigest, bool, toBool)
    CREATE_CONFIG_MEMBERS_EX(Logging_ImrServerDumpBodySizeLimit, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Logging_McuInjectDigest, bool, toBool)
    CREATE_CONFIG_MEMBERS_EX(Calibration_PressureCalMaxTravelUntilEngaged, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Calibration_PressureCalMaxTravelUntilDataReady, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Calibration_PressureCalInjectVolume, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Calibration_PressureCalADCRangeMin, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Calibration_PressureCalADCRangeMax, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Calibration_PressureCalMovingMeanSampleSize, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Hidden_MaxSteps, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Hidden_MaxPhases, int, toInt)
    CREATE_CONFIG_MEMBERS_EX(Hidden_InjectionPhaseFlowRateMin, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Hidden_InjectionPhaseFlowRateMax, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Hidden_InjectionPhaseVolMin, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Hidden_InjectionPhaseVolMax, double, toDouble)
    CREATE_CONFIG_MEMBERS_EX(Hidden_InjectionPhaseDelayMsMin, quint64, toLongLong)
    CREATE_CONFIG_MEMBERS_EX(Hidden_InjectionPhaseDelayMsMax, quint64, toLongLong)
    CREATE_CONFIG_MEMBERS(Hidden_InjectionPressureKpaMin)
    CREATE_CONFIG_MEMBERS(Hidden_InjectionPressureKpaMax)

private:
    EnvGlobal *env;
    EnvLocal *envLocal;
    Config *db;

    void initConfig();
    void emitAllConfigChanged();

private slots:
    void slotAppStarted();
    void slotAppInitialised();
};

#endif // DS_CAPABILITIES_H
