#ifndef IMR_PARSER_H
#define IMR_PARSER_H

#include "DataServices/Exam/DS_ExamDef.h"
#include "DataServices/Device/DS_DeviceDef.h"
#include "DataServices/Mcu/DS_McuDef.h"
#include "DataServices/Alert/DS_AlertDef.h"
#include "DataServices/Cru/DS_CruDef.h"
#include "DataServices/Mwl/DS_MwlDef.h"
#include "DataServices/Test/DS_TestDef.h"
#include "DataServices/Upgrade/DS_UpgradeDef.h"
#include "DataServices/Workflow/DS_WorkflowDef.h"
#include "Common/Config.h"

class ImrParser
{
public:
    // Enum Parser: To CPP
    static DS_DeviceDef::FluidSourceIdx ToCpp_FluidSourceIdx(QString from);
    static SyringeIdx ToCpp_FluidSourceSyringeIdx(QString from);
    static DS_DeviceDef::FluidSourceDisposableType ToCpp_FluidSourceDisposableType(QString from);
    static DS_SystemDef::StatePath ToCpp_StatePath(QString from);
    static DS_ExamDef::InjectionPlanDigestState ToCpp_InjectionPlanDigestState(QString from);
    static DS_ExamDef::InjectionPersonalizationInputSource ToCpp_InjectionPersonalizationInputSource(QString from);
    static DS_ExamDef::InjectionPersonalizationNoticeType ToCpp_InjectionPersonalizationNoticeType(QString from);
    static DS_ExamDef::InjectionPersonalizationNoticeImportance ToCpp_InjectionPersonalizationNoticeImportance(QString from);
    static DS_ExamDef::InjectionPhaseType ToCpp_InjectionPhaseType(QString from);
    static DS_ExamDef::StepTerminationReason ToCpp_StepTerminationReason(QString from);
    static DS_ExamDef::InjectionPhaseProgressState ToCpp_InjectionPhaseProgressState(QString from);
    static DS_ExamDef::TimedReminderDisplayHint ToCpp_TimedReminderDisplayHint(QString from);
    static DS_ExamDef::ScannerInterfaceStatus ToCpp_ScannerInterfaceStatus(QString from);
    static DS_ExamDef::ScannerInterfaceMode ToCpp_ScannerInterfaceMode(QString from);
    static DS_ExamDef::ExamProgressState ToCpp_ExamProgressState(QString from);
    static DS_CruDef::CruLicensedFeature ToCpp_CruLicensedFeature(QString from);
    static DS_CruDef::CruLinkType ToCpp_CruLinkType(QString from);
    static DS_CruDef::CruLinkState ToCpp_CruLinkState(QString from);
    static DS_CruDef::CruLinkQuality ToCpp_CruLinkQuality(QString from);
    static DS_McuDef::InjectionPhaseType ToCpp_McuInjectionPhaseType(QString from);
    static DS_McuDef::InjectorState ToCpp_InjectorState(QString from);
    static DS_McuDef::InjectionCompleteReason ToCpp_InjectionCompleteReason(QString from);
    static DS_McuDef::StopcockPos ToCpp_StopcockPos(QString from);
    static DS_McuDef::PlungerState ToCpp_PlungerState(QString from);
    static DS_McuDef::SyringeState ToCpp_SyringeState(QString from);
    static DS_McuDef::BatteryLevel ToCpp_McuBatteryLevel(QString from);
    static DS_McuDef::DoorState ToCpp_DoorState(QString from);
    static DS_McuDef::WasteBinState ToCpp_WasteBinState(QString from);
    static bool ToCpp_AdaptiveFlowActive(QString from);
    static bool ToCpp_MudsPresent(QString from);
    static bool ToCpp_MudsLatched(QString from);
    static bool ToCpp_SudsInserted(QString from);
    static bool ToCpp_SudsbubbleDetected(QString from);
    static bool ToCpp_PrimeBtnPressed(QString from);
    static bool ToCpp_StopBtnPressed(QString from);
    static bool ToCpp_DoorBtnPressed(QString from);
    static DS_McuDef::BottleBubbleDetectorState ToCpp_BubbleState(QString from);
    static DS_McuDef::OutletDoorState ToCpp_OutletDoorState(QString from);
    static DS_McuDef::HeatMaintainerState ToCpp_HeatMaintainerState(QString from);
    static bool ToCpp_IsShutdown(QString from);
    static DS_ExamDef::AdaptiveFlowState ToCpp_AdaptiveFlowState(QString from);
    static DS_McuDef::AdaptiveFlowState ToCpp_McuAdaptiveFlowState(QString from);
    static DS_McuDef::PressureLimitSensitivityType ToCpp_PressureLimitSensitivityType(QString from);
    static DS_TestDef::TestType ToCpp_TestType(QString from);

    // Enum Parser: To IMR
    static QString ToImr_FluidSourceIdx(DS_DeviceDef::FluidSourceIdx from);
    static QString ToImr_FluidSourceSyringeIdx(SyringeIdx from);
    static QString ToImr_FluidSourceBottleIdx(SyringeIdx from);
    static QString ToImr_FluidSourceDisposableType(DS_DeviceDef::FluidSourceDisposableType from);
    static QString ToImr_StatePath(DS_SystemDef::StatePath from);
    static QString ToImr_InjectionPlanDigestState(DS_ExamDef::InjectionPlanDigestState from);
    static QString ToImr_InjectionPersonalizationInputSource(DS_ExamDef::InjectionPersonalizationInputSource from);
    static QString ToImr_InjectionPersonalizationNoticeType(DS_ExamDef::InjectionPersonalizationNoticeType from);
    static QString ToImr_InjectionPersonalizationNoticeImportance(DS_ExamDef::InjectionPersonalizationNoticeImportance from);
    static QString ToImr_ExamProgressState(DS_ExamDef::ExamProgressState from);
    static QString ToImr_InjectionPhaseType(DS_ExamDef::InjectionPhaseType from);
    static QString ToImr_ArmType(DS_ExamDef::ArmType from);
    static QString ToImr_StepTerminationReason(DS_ExamDef::StepTerminationReason from);
    static QString ToImr_TimedReminderDisplayHint(DS_ExamDef::TimedReminderDisplayHint from);
    static QString ToImr_ScannerInterfaceStatus(DS_ExamDef::ScannerInterfaceStatus from);
    static QString ToImr_ScannerInterfaceMode(DS_ExamDef::ScannerInterfaceMode from);
    static QString ToImr_InjectionPhaseProgressState(DS_ExamDef::InjectionPhaseProgressState from);
    static QString ToImr_BatteryLevel(DS_McuDef::BatteryLevel from);
    static QString ToImr_HeatMaintainerState(DS_McuDef::HeatMaintainerState from);
    static QString ToImr_CruLinkType(DS_CruDef::CruLinkType from);
    static QString ToImr_CruLinkState(DS_CruDef::CruLinkState from);
    static QString ToImr_CruLinkQuality(DS_CruDef::CruLinkQuality from);
    static QString ToImr_StopcockPos(DS_McuDef::StopcockPos from);
    static QString ToImr_McuLinkState(DS_McuDef::LinkState from);
    static QString ToImr_DoorState(DS_McuDef::DoorState from);
    static QString ToImr_WasteBinState(DS_McuDef::WasteBinState from);
    static QString ToImr_OutletDoorState(DS_McuDef::OutletDoorState from);
    static QString ToImr_PlungerState(DS_McuDef::PlungerState from);
    static QString ToImr_SyringeState(DS_McuDef::SyringeState from);
    static QString ToImr_InjectionPhaseType(DS_McuDef::InjectionPhaseType from);
    static QString ToImr_InjectorState(DS_McuDef::InjectorState from);
    static QString ToImr_InjectionCompleteReason(DS_McuDef::InjectionCompleteReason from);
    static QString ToImr_BottleBubbleDetectorState(DS_McuDef::BottleBubbleDetectorState from);
    static QString ToImr_PressureCalibrationState(DS_McuDef::PressureCalibrationState from);
    static QString ToImr_LedIndex(LedIndex from);
    static QString ToImr_LedControlType(DS_McuDef::LedControlType from);
    static QString ToImr_HeatMaintainerIndex(HeatMaintainerIdx from);
    static QString ToImr_DataServiceActionState(DataServiceActionStateType from);
    static QString ToImr_UpgradeState(DS_UpgradeDef::UpgradeState from);
    static QString ToImr_WorkFlowState(DS_WorkflowDef::WorkflowState from);
    static QString ToImr_WorkflowErrorState(DS_WorkflowDef::WorkflowErrorState from);
    static QString ToImr_SodErrorState(DS_WorkflowDef::SodErrorState from);
    static QString ToImr_MudsSodState(DS_WorkflowDef::MudsSodState from);
    static QString ToImr_SudsAirRecoveryState(DS_WorkflowDef::SudsAirRecoveryState from);
    static QString ToImr_FluidRemovalState(DS_WorkflowDef::FluidRemovalState from);
    static QString ToImr_EndOfDayPurgeState(DS_WorkflowDef::EndOfDayPurgeState from);
    static QString ToImr_AutoEmptyState(DS_WorkflowDef::AutoEmptyState from);
    static QString ToImr_MudsEjectState(DS_WorkflowDef::MudsEjectState from);
    static QString ToImr_SyringeAirRecoveryState(DS_WorkflowDef::SyringeAirRecoveryState from);
    static QString ToImr_WorkflowBatteryState(DS_WorkflowDef::WorkflowBatteryState from);
    static QString ToImr_ManualQualifiedDischargeState(DS_WorkflowDef::ManualQualifiedDischargeState from);
    static QString ToImr_ShippingModeState(DS_WorkflowDef::ShippingModeState from);
    static QString ToImr_AutomaticQualifiedDischargeState(DS_WorkflowDef::AutomaticQualifiedDischargeState from);
    static QString ToImr_PreloadProtocolState(DS_WorkflowDef::PreloadProtocolState from);
    static QString ToImr_SudsPrimeType(DS_DeviceDef::SudsPrimeType from);
    static QString ToImr_McuInjectionPhaseType(const DS_McuDef::InjectionPhaseType from);
    static QString ToImr_PowerControlType(const DS_McuDef::PowerControlType from);
    static QString ToImr_FillType(DS_McuDef::FillType from);
    static QString ToImr_AdaptiveFlowState(DS_ExamDef::AdaptiveFlowState from);
    static QString ToImr_McuAdaptiveFlowState(DS_McuDef::AdaptiveFlowState from);
    static QString ToImr_PressureLimitSensitivityType(DS_McuDef::PressureLimitSensitivityType from);
    static QString ToImr_TestType(DS_TestDef::TestType from);

    // Data Parser: To CPP
    static Config::ValidRange ToCpp_ConfigItemValidRange(const QVariantMap &from, QString *err = NULL);
    static Config::Item ToCpp_ConfigItem(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::InjectionPersonalizationInput ToCpp_InjectionPersonalizationInput(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::InjectionPersonalizationInputs ToCpp_InjectionPersonalizationInputs(const QVariantList &from, QString *err = NULL);
    static DS_ExamDef::InjectionPersonalizationNotice ToCpp_InjectionPersonalizationNotice(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::InjectionPersonalizationNotices ToCpp_InjectionPersonalizationNotices(const QVariantList &from, QString *err = NULL);
    static DS_ExamDef::SharingInformation ToCpp_SharingInformation(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::InjectionPhase ToCpp_InjectionPhase(const QVariantMap &from, QString *err = NULL, bool setMissingFields = false);
    static DS_ExamDef::InjectionStep ToCpp_InjectionStep(const QVariantMap &from, QString *err = NULL, bool setMissingFields = false);
    static DS_ExamDef::InjectionPlan ToCpp_InjectionPlan(const QVariantMap &from, QString *err = NULL, bool setMissingFields = false);
    static DS_ExamDef::InjectionPlanDigest ToCpp_InjectionPlanDigest(const QVariantMap &from, QString *err = NULL, bool setMissingFields = false);
    static DS_ExamDef::InjectionPlanDigests ToCpp_InjectionPlanDigests(const QVariantList &from, QString *err = NULL, bool setMissingFields = false);
    static DS_ExamDef::InjectionPlanTemplateGroup ToCpp_InjectionPlanTemplateGroup(const QVariantMap &from, QString *err = NULL, bool setMissingFields = false);
    static DS_ExamDef::InjectionPlanTemplateGroups ToCpp_InjectionPlanTemplateGroups(const QVariantList &from, QString *err = NULL, bool setMissingFields = false);
    static DS_ExamDef::PhaseProgressDigest ToCpp_PhaseProgressDigest(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::ExecutedStep ToCpp_ExecutedStep(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::ExecutedSteps ToCpp_ExecutedSteps(const QVariantList &from, QString *err = NULL);
    static DS_ExamDef::Reminder ToCpp_Reminder(const QVariantMap &from, QString *errStr = NULL);
    static DS_ExamDef::ScannerInterlocks ToCpp_ScannerInterlocks(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::WorklistDetails ToCpp_WorklistDetails(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::ExamField ToCpp_ExamField(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::ExamFieldMap ToCpp_ExamFieldMap(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::ExamFieldParameter ToCpp_ExamFieldParameter(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::LinkedAccession ToCpp_LinkedAccession(const QVariantMap &from, QString *err = NULL);
    static DS_ExamDef::LinkedAccessions ToCpp_LinkedAccessions(const QVariantList &from, QString *err = NULL);
    static DS_ExamDef::ExamAdvanceInfo ToCpp_ExamAdvanceInfo(const QVariantMap &from, QString *err = NULL);
    static DS_DeviceDef::FluidSources ToCpp_FluidSources(const QVariantMap &from, QString *err);
    static DS_DeviceDef::FluidSource ToCpp_FluidSource(const QVariantMap &from, QString *err);
    static DS_DeviceDef::FluidOptions ToCpp_FluidOptions(const QVariantMap &from, QString *err = NULL);
    static DS_DeviceDef::FluidFamilies ToCpp_FluidFamilies(const QVariantList &from, QString *err);
    static DS_DeviceDef::FluidFamily ToCpp_ContrastFamily(const QVariantMap &from, QString *err);
    static DS_DeviceDef::FluidPackage ToCpp_FluidPackage(const QVariantMap &from, QString *err = NULL);
    static DS_DeviceDef::FluidPackages ToCpp_FluidPackages(const QVariantList &from, QString *err);
    static DS_DeviceDef::KnownBarcodes ToCpp_KnownBarcodes(const QVariantMap &from, QString *err);
    static DS_CruDef::CruLicensedFeatures ToCpp_CruLicensedFeatures(const QVariantList &from, QString *err = NULL);
    static DS_CruDef::CruLinkStatus ToCpp_CruLinkStatus(const QVariantMap &from, QString *err = NULL);
    static DS_McuDef::InjectionCompleteStatus ToCpp_InjectionCompleteStatus(QString from, QString *err = NULL);
    static DS_McuDef::ActLedParams ToCpp_ActLedParams(QString from, QString *err = NULL);
    static DS_McuDef::LedControlStatus ToCpp_LedControlStatus(const QVariantMap &from, QString *err = NULL);
    static DS_WorkflowDef::SyringeSodStatus ToCpp_SyringeSodStatus(const QVariantMap &from, QString *err = NULL);
    static DS_WorkflowDef::MudsSodStatus ToCpp_MudsSodStatus(const QVariantMap &from, QString *err = NULL);
    static DS_MwlDef::DicomField ToCpp_DicomField(const QVariantMap &from, QString *err = NULL);
    static DS_MwlDef::DicomFields ToCpp_DicomFields(const QVariantList &from, QString *err = NULL);
    static DS_MwlDef::DicomFieldMap ToCpp_DicomFieldMap(const QVariantMap &from, QString *err = NULL);
    static DS_MwlDef::WorklistEntry ToCpp_WorklistEntry(const QVariantMap &from, QString *err = NULL);
    static DS_MwlDef::WorklistEntries ToCpp_WorklistEntries(const QVariantList &from, QString *err = NULL);
    static QList<double> ToCpp_DoubleList(const QVariantList &from, QString *err = NULL);

    // Data Parser: To IMR
    static QVariantMap ToImr_ConfigItemValidRange(const Config::ValidRange &from, QString *err = NULL);
    static QVariantMap ToImr_ConfigItem(const Config::Item &from, QString *err = NULL);
    static QString ToImr_InjectionCompleteStatus(const DS_McuDef::InjectionCompleteStatus &from, QString *err = NULL);
    static QVariantMap ToImr_TemperatureReadings(const DS_McuDef::TemperatureReadings &from, QString *err = NULL);
    static QVariantMap ToImr_HeatMaintainerStatus(const DS_McuDef::HeatMaintainerStatus &from, QString *err = NULL);
    static QVariantMap ToImr_PhaseProgressDigest(const DS_ExamDef::PhaseProgressDigest &from, QString *err = NULL);
    static QVariantMap ToImr_ExecutedStep(const DS_ExamDef::ExecutedStep &from, QString *err = NULL);
    static QVariantList ToImr_ExecutedSteps(const DS_ExamDef::ExecutedSteps &from, QString *err = NULL);
    static QVariantMap ToImr_FluidSourceSyringes(const DS_DeviceDef::FluidSources &from, QString *err = NULL);
    static QVariantMap ToImr_FluidSourceBottles(const DS_DeviceDef::FluidSources &from, QString *err = NULL);
    static QVariantMap ToImr_FluidSource(const DS_DeviceDef::FluidSource &from, DS_DeviceDef::FluidSourceIdx fluidSrcFilter, QString *err = NULL);
    static QVariantMap ToImr_FluidSource(const DS_DeviceDef::FluidSource &from, QString *err = NULL);
    static QVariantMap ToImr_FluidSources(const DS_DeviceDef::FluidSources &from, QString *err = NULL);
    static QVariantMap ToImr_FluidOptions(const DS_DeviceDef::FluidOptions &from, QString *err = NULL);
    static QVariantList ToImr_FluidFamilies(const DS_DeviceDef::FluidFamilies &from, QString *err = NULL);
    static QVariantMap ToImr_ContrastFamily(const DS_DeviceDef::FluidFamily &from, QString *err = NULL);
    static QVariantMap ToImr_FluidPackage(const DS_DeviceDef::FluidPackage &from, QString *err = NULL);
    static QVariantList ToImr_FluidPackages(const DS_DeviceDef::FluidPackages &from, QString *err = NULL);
    static QVariantMap ToImr_FluidInfo(const DS_DeviceDef::FluidInfo &from, QString *err = NULL);
    static QVariantMap ToImr_KnownBarcodes(const DS_DeviceDef::KnownBarcodes &from, QString *err = NULL);
    static QVariantList ToImr_FluidSourceSelectItems(const DS_DeviceDef::FluidSelectItems &from, QString *err = NULL);
    static QVariantList ToImr_FluidSourceSelectItems(const DS_DeviceDef::FluidPackages &from, QString *err = NULL);
    static QVariantMap ToImr_PowerStatus(const DS_McuDef::PowerStatus &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionRequestProcessStatus(const DS_ExamDef::InjectionRequestProcessStatus &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionPersonalizationInput(const DS_ExamDef::InjectionPersonalizationInput &from, QString *err = NULL);
    static QVariantList ToImr_InjectionPersonalizationInputs(const DS_ExamDef::InjectionPersonalizationInputs &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionPersonalizationNotice(const DS_ExamDef::InjectionPersonalizationNotice &from, QString *err = NULL);
    static QVariantList ToImr_InjectionPersonalizationNotices(const DS_ExamDef::InjectionPersonalizationNotices &from, QString *err = NULL);
    static QVariantMap ToImr_SharingInformation(const DS_ExamDef::SharingInformation &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionPhase(const DS_ExamDef::InjectionPhase &from, QString *err = NULL);
    static QVariantList ToImr_InjectionPhases(const DS_ExamDef::InjectionPhases &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionStep(const DS_ExamDef::InjectionStep &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionPlan(const DS_ExamDef::InjectionPlan &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionPlanDigest(const DS_ExamDef::InjectionPlanDigest &from, QString *err = NULL);
    static QVariantList ToImr_InjectionPlanDigests(const DS_ExamDef::InjectionPlanDigests &from, QString *err = NULL);
    static QVariantMap ToImr_InjectionPlanTemplateGroup(const DS_ExamDef::InjectionPlanTemplateGroup &from, QString *err = NULL);
    static QVariantList ToImr_InjectionPlanTemplateGroups(const DS_ExamDef::InjectionPlanTemplateGroups &from, QString *err = NULL);
    static QVariantMap ToImr_Reminder(const DS_ExamDef::Reminder &from, QString *err = NULL);
    static QVariantList ToImr_Reminders(const DS_ExamDef::Reminders &from, QString *err = NULL);
    static QVariantMap ToImr_ScannerInterlocks(const DS_ExamDef::ScannerInterlocks &from, QString *err = NULL);
    static QVariantMap ToImr_WorklistDetails(const DS_ExamDef::WorklistDetails &from, QString *err = NULL);
    static QVariantMap ToImr_ExamField(const DS_ExamDef::ExamField &from, QString *err = NULL);
    static QVariantMap ToImr_ExamFieldMap(const DS_ExamDef::ExamFieldMap &from, QString *err = NULL);
    static QVariantMap ToImr_ExamFieldParameter(const DS_ExamDef::ExamFieldParameter &from, QString *err = NULL);
    static QVariantMap ToImr_LinkedAccession(const DS_ExamDef::LinkedAccession &from, QString *err = NULL);
    static QVariantList ToImr_LinkedAccessions(const DS_ExamDef::LinkedAccessions &from, QString *err = NULL);
    static QVariantMap ToImr_ExamAdvanceInfo(const DS_ExamDef::ExamAdvanceInfo &from, QString *err = NULL);
    static QVariantMap ToImr_CruLinkStatus(const DS_CruDef::CruLinkStatus &from, QString *err = NULL);
    static QVariantList ToImr_StopcockPosAll(const DS_McuDef::StopcockPosAll &from, QString *err = NULL);
    static QString ToImr_SimDigestStr(const DS_McuDef::SimDigest &from, QString *err = NULL);
    static QString ToImr_InjectDigestStr(const DS_McuDef::InjectDigest &from, QString *err = NULL);
    static QVariantMap ToImr_PressureCalibrationStageParams(const DS_McuDef::PressureCalibrationStageParams &from, QString *err = NULL);
    static QVariantList ToImr_PressureCalibrationStagesParams(const DS_McuDef::PressureCalibrationStagesParams &from, QString *err = NULL);
    static QVariantMap ToImr_PressureCalibrationDataCheckInfo(const DS_McuDef::PressureCalibrationDataCheckInfo &from, QString *err = NULL);
    static QVariantMap ToImr_PressureCalibrationStatus(const DS_McuDef::PressureCalibrationStatus &from, QString *err = NULL);
    static QVariantList ToImr_SyringeStates(const DS_McuDef::SyringeStates &from, QString *err = NULL);
    static QVariantList ToImr_PlungerStates(const DS_McuDef::PlungerStates &from, QString *err = NULL);
    static QVariantList ToImr_BottleBubbleDetectorStates(const DS_McuDef::BottleBubbleDetectorStates &from, QString *err = NULL);
    static QVariantList ToImr_DoubleList(const QList<double> &from, QString *err = NULL);
    static QVariantMap ToImr_TestStatus(const DS_TestDef::TestStatus &from, QString *err = NULL);
    static QString ToImr_McuActLedParams(const DS_McuDef::ActLedParams &from, QString *err = NULL);
    static QVariantMap ToImr_ActLedParams(const DS_McuDef::ActLedParams &from, QString *err = NULL);
    static QVariantMap ToImr_ActPrimeParams(const DS_McuDef::ActPrimeParams &from, QString *err = NULL);
    static QVariantList ToImr_ActPrimeParamsList(const DS_McuDef::ActPrimeParamsList &from, QString *err = NULL);
    static QVariantMap ToImr_LedControlStatus(const DS_McuDef::LedControlStatus &from, QString *err = NULL);
    static QVariantMap ToImr_DataServiceActionStatus(const DataServiceActionStatus &from, QString *err = NULL);
    static QString ToImr_DataServiceActionStatusStr(const DataServiceActionStatus &from, QString *err = NULL);
    static QVariantMap ToImr_SyringeSodStatus(const DS_WorkflowDef::SyringeSodStatus &from, QString *err = NULL);
    static QVariantMap ToImr_MudsSodStatus(const DS_WorkflowDef::MudsSodStatus &from, QString *err = NULL);
    static QVariantMap ToImr_UpgradeStatus(const DS_UpgradeDef::UpgradeStatus &from, QString *err = NULL);
    static QVariantMap ToImr_UpgradeDigest(const DS_UpgradeDef::UpgradeDigest &from, QString *err = NULL);
    static QVariantMap ToImr_BarcodeInfo(const DS_DeviceDef::BarcodeInfo &from, QString *err = NULL);
    static QVariantMap ToImr_WorkflowErrorStatus(const DS_WorkflowDef::WorkflowErrorStatus &from);
    static QVariantMap ToImr_McuInjectionPhase(const DS_McuDef::InjectionPhase &from);
    static QVariantList ToImr_McuInjectionPhases(const DS_McuDef::InjectionPhases &from);
    static QVariantMap ToImr_McuInjectionProtocol(const DS_McuDef::InjectionProtocol &from);
    static QVariantMap ToImr_McuInjectorStatus(const DS_McuDef::InjectorStatus &from);
    static QVariantList ToImr_SyringeAirCheckCalDigests(const DS_McuDef::SyringeAirCheckCalDigests &from, QString *err = NULL);
    static QVariantMap ToImr_SyringeAirCheckCalData(const DS_McuDef::SyringeAirCheckCalData &from, QString *err = NULL);
    static QVariantList ToImr_SyringeAirCheckCoeffDigests(const DS_McuDef::SyringeAirCheckCoeffDigests &from, QString *err = NULL);
    static QVariantMap ToImr_SyringeAirCheckCoeff(const DS_McuDef::SyringeAirCheckCoeff &from, QString *err = NULL);
    static QVariantList ToImr_SyringeAirCheckDigests(const DS_McuDef::SyringeAirCheckDigests &from, QString *err = NULL);
    static QVariantMap ToImr_SyringeAirCheckDigest(const DS_McuDef::SyringeAirCheckDigest &from, QString *err = NULL);
    static QVariantList ToImr_PressureCalCoeffDigests(const DS_McuDef::PressureCalCoeffDigests &from, QString *err = NULL);
    static QVariantMap ToImr_PressureCalCoeff(const DS_McuDef::PressureCalCoeff &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsDeviceInfo(const DS_McuDef::BMSDigestParamsDeviceInfo &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsSBSStatus(const DS_McuDef::BMSDigestParamsSBSStatus &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsSafetyStatus(const DS_McuDef::BMSDigestParamsSafetyStatus &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsPfStatus(const DS_McuDef::BMSDigestParamsPfStatus &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsOperationStatus(const DS_McuDef::BMSDigestParamsOperationStatus &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsChargingStatus(const DS_McuDef::BMSDigestParamsChargingStatus &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsGaugingStatus(const DS_McuDef::BMSDigestParamsGaugingStatus &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigestParamsManufacturingStatus(const DS_McuDef::BMSDigestParamsManufacturingStatus &from, QString *err = NULL);
    static QVariantMap ToImr_BMSDigest(const DS_McuDef::BMSDigest &from, QString *err = NULL);
    static QVariantList ToImr_BMSDigests(const DS_McuDef::BMSDigests &from, QString *err = NULL);
    static QVariantMap ToImr_DicomField(const DS_MwlDef::DicomField &from, QString *err = NULL);
    static QVariantList ToImr_DicomFields(const DS_MwlDef::DicomFields &from, QString *err = NULL);
    static QVariantMap ToImr_DicomFieldMap(const DS_MwlDef::DicomFieldMap &from, QString *err = NULL);
    static QVariantMap ToImr_WorklistEntry(const DS_MwlDef::WorklistEntry &from, QString *err = NULL);
    static QVariantList ToImr_WorklistEntries(const DS_MwlDef::WorklistEntries &from, QString *err = NULL);
    static QVariantMap ToImr_NetworkSettingParams(const DS_SystemDef::NetworkSettingParams &from, QString *err = NULL);
    static QVariantMap ToImr_ManualQualifiedDischargeStatus(const DS_WorkflowDef::ManualQualifiedDischargeStatus &from, QString *msg = NULL);
    static QVariantMap ToImr_AutomaticQualifiedDischargeStatus(const DS_WorkflowDef::AutomaticQualifiedDischargeStatus &from, QString *msg = NULL);
    static QVariantMap ToImr_WorkflowBatteryStatus(const DS_WorkflowDef::WorkflowBatteryStatus &from, QString *msg = NULL);
    static QVariantMap ToImr_ShippingModeStatus(const DS_WorkflowDef::ShippingModeStatus &from, QString *msg = NULL);
    static QVariantMap ToImr_Iwconfig(const DS_SystemDef::IwconfigParams &from, QString *err = NULL);
};

#endif // IMR_PARSER_H
